In [1]:
import tensorflow as tf
from tensorflow import keras

## 4.1 数据类型
### 4.1.1 数值类型

In [2]:
a = 1.2 # python语言创建标量
aa = tf.constant(1.2) # tf方式创建标量
type(a), type(aa), tf.is_tensor(aa)

(float, tensorflow.python.framework.ops.EagerTensor, True)

通过`print(x)`或`x`的方式可以打印出张量x的信息

In [3]:
x = tf.constant([1, 2., 3.3])
x # 打印TF张量的相关信息

<tf.Tensor: id=1, shape=(3,), dtype=float32, numpy=array([1. , 2. , 3.3], dtype=float32)>

其中id是Tensorflow中内部索引对象的编号，shape表示张量的形状，dtype表示张量的数字精确度，张量numpy()方法可以返回Numpy.array类型的数据，方便导出数据到系统的其他模块

In [4]:
x.numpy()

array([1. , 2. , 3.3], dtype=float32)

与标量不同，向量的定义须通过List容器传给tf.constant()函数

In [5]:
# 创建一个元素的向量
a = tf.constant([1.2])
a, a.shape

(<tf.Tensor: id=2, shape=(1,), dtype=float32, numpy=array([1.2], dtype=float32)>,
 TensorShape([1]))

In [6]:
# 创建三个元素的向量
a = tf.constant([1, 2, 3.])
a, a.shape

(<tf.Tensor: id=3, shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>,
 TensorShape([3]))

In [7]:
# 使用同样的方法，定义矩阵的实现
a = tf.constant([[1, 2], [3, 4]]) # 创建2行2列的矩阵
a, a.shape

(<tf.Tensor: id=4, shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>, TensorShape([2, 2]))

In [8]:
# 创建三维张量
a = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a, a.shape

(<tf.Tensor: id=5, shape=(2, 2, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]])>, TensorShape([2, 2, 2]))

### 4.1.2 字符串类型
通过传入字符串对象即可创建字符串类型的张量

In [9]:
a = tf.constant('Hello, Deep Learning.')
a

<tf.Tensor: id=6, shape=(), dtype=string, numpy=b'Hello, Deep Learning.'>

在tf.strings模块中，提供了常见的字符串工具函数，如小写化lower()，拼接join(),长度length(),切分split()等

In [10]:
tf.strings.lower(a)

<tf.Tensor: id=7, shape=(), dtype=string, numpy=b'hello, deep learning.'>

### 4.1.3 布尔类型
TensorFlow还支持布尔类型的张量。布尔类型张量只需传入Python语言的布尔类型，转换成TensorFlow内部布尔型即可

In [11]:
a = tf.constant(True)
a

<tf.Tensor: id=8, shape=(), dtype=bool, numpy=True>

In [12]:
# 创建布尔型向量
a = tf.constant([True, False])
a

<tf.Tensor: id=9, shape=(2,), dtype=bool, numpy=array([ True, False])>

TensorFlow的布尔型和Python语言的布尔型**并不等价**，不能通用

In [13]:
a = tf.constant(True) # 创建TF布尔类型
print(a is True) # TF布尔类型张量与python布尔型比较
print(a == True) # 仅值比较

False
tf.Tensor(True, shape=(), dtype=bool)


# 4.2 数值精度
对于数值类型的张量，可以保存不同字节长度的精确度，如浮点型数3.14既可以保存为16位(Bit)长度，也可以保存为32位甚至64位精确度。位越长，精确度越高，同时占用的内存空间也越大。常用的精度类型有tf.int16、tf.int32、tf.int64、tf.float16、tf.float32、tf.float64等，其中tf.float64即为tf.double

In [14]:
# 在创建张量时，可以指定张量的保存精度
tf.constant(123456789, dtype=tf.int16)

<tf.Tensor: id=13, shape=(), dtype=int16, numpy=-13035>

In [15]:
tf.constant(123456789, dtype=tf.int32)

<tf.Tensor: id=14, shape=(), dtype=int32, numpy=123456789>

可以看出，保存精度过低时，数据123456789发生了溢出，得到了错误的结果，一搬使用tf.int32、tf.float64精度。对于浮点数，高精度的张量可以表示更精确的数据

### 4.2.1 读取精度
通过访问张量的dtype成员属性可以判断张量的保存精度

In [16]:
print('before:', a.dtype) # 读取原有张量的数值精度
if a.dtype != tf.float32:
    a = tf.cast(a, tf.float32) # 使用tf.cast函数可以
print('after:', a.dtype)

before: <dtype: 'bool'>
after: <dtype: 'float32'>


### 4.2.2 类型转换
类型转换需通过tf.cast函数完成，进行类型转换时需要保证转换操作的合法性，例如将高精度的张量转换成为低精度的张量时，可能发生数据溢出隐患

## 4.3 待优化张量
通过tf.Variable()可以将普通张量转换为待优化张量

In [17]:
a = tf.constant([-1, 0, 1, 2]) # 创建TF张量
aa = tf.Variable(a) # 转为Variable类型张量
aa.name, aa.trainable # Variable张量的属性

('Variable:0', True)

除了通过普通张量方式创建Variable，也可以直接创建

In [18]:
a = tf.Variable([[1, 2], [3, 4]])
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>


待优化张量可以视为普通张量的特殊类型，普通张量其实也可以通过GradientTape.watch()方法临时加入跟踪梯度信息的列表，从而支持自动求导功能

## 4.4 创建张量
### 4.4.1 从数组、列表对象创建
通过tf.convert_to_tensor函数可以创建新Tensor，并将保存在Python List对象或者Numpy Array对象中的数据带入到新的Tensor中

In [19]:
tf.convert_to_tensor([1, 2.]) # 从列表创建张量

<tf.Tensor: id=32, shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [20]:
import numpy as np
tf.convert_to_tensor(np.array([[1, 2.], [3, 4]])) #从数组中创建张量

<tf.Tensor: id=33, shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

需要注意的是，Numpy浮点数组默认使用64位精度保存数据，转换到Tensor类型时精度为tf.float64，可以在需要的时候将其转换为tf.float32类型

### 4.4.2 创建全0或全1长张量
将张量创建为全0或者全1数据是非常常见的张量初始化手段。考虑线性变换y = Wx + b ，将权值矩阵 W 初始化为全1矩阵，偏置 b 初始化为全0向量，此时线性变化层输出 y = x ，因此是一种比较好的层初始化状态。通过tf.zeros()和tf.ones()即可创建任意形状，且内容全0或全1的张量

In [21]:
tf.zeros([]), tf.ones([])

(<tf.Tensor: id=34, shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: id=35, shape=(), dtype=float32, numpy=1.0>)

In [22]:
# 创建全0和全1的向量
tf.zeros([1]), tf.ones([2])

(<tf.Tensor: id=38, shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Tensor: id=41, shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>)

In [23]:
tf.zeros([2, 2]), tf.ones([3, 2])

(<tf.Tensor: id=44, shape=(2, 2), dtype=float32, numpy=
 array([[0., 0.],
        [0., 0.]], dtype=float32)>,
 <tf.Tensor: id=47, shape=(3, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>)

通过tf.zeros_like，tf.ones_like可以方便的新建与某个张量shape一致，且内容为全0或者全1的张量。

In [24]:
a = tf.ones([2, 3])
tf.zeros_like(a)

<tf.Tensor: id=51, shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### 4.4.3 创建自定义数值张量
通过tf.fill(shape, value)可以创建全为自定义数值value的张量，形状由shape参数指定

In [25]:
tf.fill([], -1) # 创建-1的标量

<tf.Tensor: id=54, shape=(), dtype=int32, numpy=-1>

### 4.4.4 创建已知分布的张量
正态分布和均值分布是最常见的分布之一，创建采样自这2种分布的张量非常有用，比如在卷积神经网络中，卷积核张量W初始化为正态分布；在对抗生产网络中，隐藏层变量z一般采样自均值分布

通过tf.random.normal(shape, mean=0.0, stddev=1.0)可以创建形状为shape，均值为mean，标准差为stddev的正态分布N。

In [26]:
tf.random.normal([2, 2])

<tf.Tensor: id=60, shape=(2, 2), dtype=float32, numpy=
array([[ 1.0869708 , -0.08471203],
       [-0.40201572,  0.226951  ]], dtype=float32)>

通过tf.random.uniform(shape, minval=0, maxval=None, dtype=tf.float32)可以创建采样自[minval, maxval)区间的均匀分布的张量

In [27]:
tf.random.uniform([2, 2]) # 创建采用自[0, 1)的均匀分布矩阵

<tf.Tensor: id=67, shape=(2, 2), dtype=float32, numpy=
array([[0.899817  , 0.84741616],
       [0.94304895, 0.22638023]], dtype=float32)>

In [28]:
tf.random.uniform([2, 2], maxval=10) # 创建采样自[0, 10)均匀分布矩阵

<tf.Tensor: id=74, shape=(2, 2), dtype=float32, numpy=
array([[9.640602 , 8.145672 ],
       [7.021474 , 3.8338327]], dtype=float32)>

### 4.4.5 创建序列
在循环计算或者对张量进行索引时，经常需要创建一段连续的整数序列，可以通过tf.range()函数实现。

tf.range(limit, delta=1)可以创建[0, limit)之间，步长为delta的整型序列

In [29]:
tf.range(10)

<tf.Tensor: id=78, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [30]:
tf.range(1, 10, 2)

<tf.Tensor: id=82, shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

## 4.5 张量的典型应用
### 4.5.1 标量
标量就是一个简单的数字，维度为0，shape为[]，标量的一些典型用途是**误差率的表示**、各种**测试指标**的表示

以均方差误差函数为例，经过tf.keras.losses.mse返回每个样本上的误差值，最后取误差的均值作为当前Batch的误差，它只是一个标量

In [31]:
out = tf.random.uniform([4, 10]) # 随机模拟网络输出
y = tf.constant([2, 3, 2, 0]) # 随机构造样本真实标签
y = tf.one_hot(y, depth=10) # one-hot编码
loss = tf.keras.losses.mse(y, out) # 计算每个样本的MSE
loss = tf.reduce_mean(loss) # 平均MSE，loss应是标量
print(loss)

tf.Tensor(0.35754168, shape=(), dtype=float32)


### 4.5.2 向量
偏置b就使用向量表示，把所有输出节点的偏置表示成向量形式 $ b = \left[ b_1, b_2 \right] ^ T $

In [32]:
# z = wx, 模拟获得激活函数的输入z
z = tf.random.normal([4, 2])
b = tf.zeros([2]) # 创建偏置向量
z = z + b # 累加上偏置向量
z

<tf.Tensor: id=109, shape=(4, 2), dtype=float32, numpy=
array([[ 0.35497734, -1.0715697 ],
       [-0.30867717,  0.5965641 ],
       [ 1.0800284 ,  2.0894403 ],
       [-1.392141  , -0.7874128 ]], dtype=float32)>

通过高层接口类Dense()方式创建的网络层，张量W和b存储在类的内部，由类自动创建并管理。可以通过全连接层的bias成员变量查看偏置b，例如创建输入节点数为4，输出节点数为3的线性层网络，那么它的偏置向量b的长度应为3

In [33]:
fc = tf.keras.layers.Dense(3) # 创建一层Wx+b，输出节点数为3
# 通过build函数创建W, b张量，输入节点为4
fc.build(input_shape=(2, 4))
fc.bias # 查看偏置向量

<tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

### 4.5.3 矩阵
矩阵也是非常常见的张量类型，比如全连接层的批量输入张量X的形状为 $ \left[b, d_{in} \right]$，其中b表示输入样本的个数，即Batch_Size, $ d_{in} $ 表示输入特征的长度。

In [34]:
x = tf.random.normal([2, 4]) # 2个样本，特征长度为4的张量
w = tf.ones([4, 3]) # 定义W张量
b = tf.zeros([3]) # 定义b张量
o = x@w + b
o

<tf.Tensor: id=147, shape=(2, 3), dtype=float32, numpy=
array([[-0.66265523, -0.66265523, -0.66265523],
       [ 1.2417035 ,  1.2417035 ,  1.2417035 ]], dtype=float32)>

在TensorFlow中可以通过Dense类直接实现全连接层 $ \sigma \left ( X@W + b \right ) $，特别地，当激活函数 $ \sigma $ 为空时，全连接层也称为线性层。我们可以通过Dense类创建输入4个节点，输出3个节点的网络层，并通过全连接层的Kernel成员名查看其权值矩阵W

In [35]:
fc = tf.keras.layers.Dense(3) # 定义全连接层的输出节点数为3
fc.build(input_shape=(2, 4))
fc.kernel

<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.07031351, -0.7961218 , -0.83275414],
       [-0.8902934 ,  0.08401394,  0.10655653],
       [-0.00588936, -0.8820179 , -0.09860969],
       [ 0.2403338 , -0.839215  ,  0.5954622 ]], dtype=float32)>

### 4.5.4 三维张量
三维的张量一个典型应用是表示序列信号，它的格式是 X = [b, sequence len, feature len] 其中b表示序列信号的数量，sequence len表示序列信号在时间维度上的采样点数或步数，feature len表示每个点的特征长度。

In [37]:
(x_train, y_train), (x_test, y_test) = keras.datasets.imdb.load_data(num_words=10000) # 自动加载IMDB电影评价数据集
# 将句子填充、截断为等长80个单词的句子
x_train = keras.preprocessing.sequence.pad_sequences(x_train, maxlen=80)
x_train.shape

17465344/17464789 [==============================] - 8s 0us/step


(25000, 80)

In [38]:
# 创建词向量Embedding层类
embedding = tf.keras.layers.Embedding(10000, 100)
# 将数字编码的单词转换为词向量
out = embedding(x_train)
out.shape

TensorShape([25000, 80, 100])

### 4.5.5 四维张量
四维张量在卷积神经网络中应用十分广泛，它用于保存特征图(Feature maps)数据，格式一般定义为 [b, h, w, c] 其中b表示输入样本的数量，h/w分别表示特征图的高/宽，c表示特征图的通道数。

In [39]:
x = tf.random.normal([4, 32, 32, 3]) # 创建32 * 32 的彩色图片输入个数为4
layer = keras.layers.Conv2D(16, kernel_size=3) # 创建卷积神经网络
out = layer(x) # 前向计算
out.shape

TensorShape([4, 30, 30, 16])

In [40]:
layer.kernel.shape # 访问卷积核张量

TensorShape([3, 3, 3, 16])

## 4.6 索引与切片

通过索引与切片操作可以提取张量的部分数据，使用频率非常高

### 4.6.1 索引

在TensorFlow中支持基本的[i][j]...标准索引方式，也支持通过逗号分隔索引号的索引方式。

In [42]:
x = tf.random.normal([4, 32, 32, 3])
print(x[0])
print(x[0][1])
print(x[0][1][2])
print(x[2][1][0][1])

tf.Tensor(
[[[ 0.9358451  -0.18618539 -0.85742205]
  [-1.4369293   2.3945692  -0.13809584]
  [-0.07258236 -0.49016306  1.615732  ]
  ...
  [ 0.8562781  -0.18121845  0.90331864]
  [ 0.10782529 -1.2000215   0.64827996]
  [ 1.019487    0.5614674   0.3659705 ]]

 [[ 0.5786742   0.57937765 -1.2847228 ]
  [-0.33243424 -0.42127576  0.98879635]
  [ 1.6769586  -0.32224828  0.73290235]
  ...
  [-0.3431775   0.7716607   0.8982969 ]
  [ 0.43976325  0.9296968  -0.9666902 ]
  [-0.79846686 -0.82033885 -0.7452553 ]]

 [[ 0.26795456  0.3958743  -0.12063207]
  [ 0.6451852   2.3712933   1.3862005 ]
  [ 0.5227435   0.59213984 -0.34021226]
  ...
  [-0.52888215  0.417686    0.18460533]
  [ 0.01772973 -0.04185007 -0.8194715 ]
  [-1.027557   -1.5185268   1.1515623 ]]

 ...

 [[-0.71366316 -0.5502357  -0.12019509]
  [ 1.7647713  -0.32990968  0.29064897]
  [-1.2607658   0.23626927  0.52281284]
  ...
  [ 2.0099618  -1.5285137   0.537436  ]
  [-0.71538156  0.31361958 -0.763305  ]
  [ 1.9095011   0.42584723 -0.452

### 4.6.2 切片
通过start:end:step切片方式可以方便地提取一段数据

In [43]:
x[1:3]

<tf.Tensor: id=316, shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[ 0.2536348 ,  0.9613802 , -0.74066764],
         [ 1.3441887 , -0.68319774, -0.06843416],
         [-1.2493814 , -1.0101233 , -0.7906423 ],
         ...,
         [-0.09210271,  1.5779675 , -0.32729697],
         [-0.16231447,  0.4092217 , -0.5080269 ],
         [ 1.112306  ,  0.19783218,  0.2649804 ]],

        [[-0.6841071 , -1.2246782 ,  0.22186257],
         [ 0.04325636, -0.13493343, -0.17881139],
         [-0.67875564,  0.8408532 ,  0.220963  ],
         ...,
         [-0.27084795, -0.07742538,  1.1287125 ],
         [-0.42117113, -0.0686627 ,  0.6794488 ],
         [-1.1624132 , -0.00828036,  0.97831666]],

        [[ 0.29933023,  0.26944834, -0.7728486 ],
         [ 0.3971441 , -0.46672922,  0.9659381 ],
         [-0.2515187 ,  0.944085  , -0.3354304 ],
         ...,
         [ 1.4515959 ,  1.6836886 ,  0.43171793],
         [ 1.1990772 , -0.2698902 ,  0.15674701],
         [-0.34955895,  0.7193056 ,  0.5

start:end:step切片方式有很多简写方式，其中start、end、step 3个参数可以跟据需要选择性地省略，全部省略时即为::，表示从最开始读取到最末尾，步长为1。如x[0,::]表示读取第一张图片的所有行，等价于x[0]