In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
a = 1.2 # python语言创建标量
aa = tf.constant(1.2) # tf方式创建标量
type(a), type(aa), tf.is_tensor(aa)

(float, tensorflow.python.framework.ops.EagerTensor, True)

通过`print(x)`或`x`的方式可以打印出张量x的信息

In [3]:
x = tf.constant([1, 2., 3.3])
x # 打印TF张量的相关信息

<tf.Tensor: id=1, shape=(3,), dtype=float32, numpy=array([1. , 2. , 3.3], dtype=float32)>

其中id是Tensorflow中内部索引对象的编号，shape表示张量的形状，dtype表示张量的数字精确度，张量numpy()方法可以返回Numpy.array类型的数据，方便导出数据到系统的其他模块

In [4]:
x.numpy()

array([1. , 2. , 3.3], dtype=float32)

与标量不同，向量的定义须通过List容器传给tf.constant()函数

In [5]:
# 创建一个元素的向量
a = tf.constant([1.2])
a, a.shape

(<tf.Tensor: id=2, shape=(1,), dtype=float32, numpy=array([1.2], dtype=float32)>,
 TensorShape([1]))

In [7]:
# 创建三个元素的向量
a = tf.constant([1, 2, 3.])
a, a.shape

(<tf.Tensor: id=4, shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>,
 TensorShape([3]))

In [9]:
# 使用同样的方法，定义矩阵的实现
a = tf.constant([[1, 2], [3, 4]]) # 创建2行2列的矩阵
a, a.shape

(<tf.Tensor: id=6, shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>, TensorShape([2, 2]))

In [12]:
# 创建三维张量
a = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a, a.shape

(<tf.Tensor: id=9, shape=(2, 2, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]])>, TensorShape([2, 2, 2]))

通过传入字符串对象即可创建字符串类型的张量

In [13]:
a = tf.constant('Hello, Deep Learning.')
a

<tf.Tensor: id=10, shape=(), dtype=string, numpy=b'Hello, Deep Learning.'>

在tf.strings模块中，提供了常见的字符串工具函数，如小写化lower()，拼接join(),长度length(),切分split()等

In [14]:
tf.strings.lower(a)

<tf.Tensor: id=11, shape=(), dtype=string, numpy=b'hello, deep learning.'>

TensorFlow还支持布尔类型的张量。布尔类型张量只需传入Python语言的布尔类型，转换成TensorFlow内部布尔型即可

In [16]:
a = tf.constant(True)
a

<tf.Tensor: id=13, shape=(), dtype=bool, numpy=True>

In [17]:
# 创建布尔型向量
a = tf.constant([True, False])
a

<tf.Tensor: id=14, shape=(2,), dtype=bool, numpy=array([ True, False])>

TensorFlow的布尔型和Python语言的布尔型**并不等价**，不能通用

In [19]:
a = tf.constant(True) # 创建TF布尔类型
print(a is True) # TF布尔类型张量与python布尔型比较
print(a == True) # 仅值比较

False
tf.Tensor(True, shape=(), dtype=bool)


对于数值类型的张量，可以保存不同字节长度的精确度，如浮点型数3.14既可以保存为16位(Bit)长度，也可以保存为32位甚至64位精确度。位越长，精确度越高，同时占用的内存空间也越大。常用的精度类型有tf.int16、tf.int32、tf.int64、tf.float16、tf.float32、tf.float64等，其中tf.float64即为tf.double

In [21]:
# 在创建张量时，可以指定张量的保存精度
tf.constant(123456789, dtype=tf.int16)

<tf.Tensor: id=23, shape=(), dtype=int16, numpy=-13035>

In [22]:
tf.constant(123456789, dtype=tf.int32)

<tf.Tensor: id=24, shape=(), dtype=int32, numpy=123456789>

可以看出，保存精度过低时，数据123456789发生了溢出，得到了错误的结果，一搬使用tf.int32、tf.float64精度。对于浮点数，高精度的张量可以表示更精确的数据

通过访问张量的dtype成员属性可以判断张量的保存精度

In [23]:
print('before:', a.dtype) # 读取原有张量的数值精度
if a.dtype != tf.float32:
    a = tf.cast(a, tf.float32) # 使用tf.cast函数可以
print('after:', a.dtype)

before: <dtype: 'bool'>
after: <dtype: 'float32'>


类型转换需通过tf.cast函数完成，进行类型转换时需要保证转换操作的合法性，例如将高精度的张量转换成为低精度的张量时，可能发生数据溢出隐患