# 5 TensorFlow 进阶
## 5.1 合并与分割
### 5.1.1 合并
张量的合并可以使用拼接和堆叠操作实现。拼接操作并不会产生新的维度，仅在现有的维度上合并，而堆叠操作会创建新维度。

In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
a = tf.random.normal([4, 35, 8])
b = tf.random.normal([6, 35, 8])
tf.concat([a, b], axis=0) # 拼接合并，按照第一个维度进行合并

<tf.Tensor: id=13, shape=(10, 35, 8), dtype=float32, numpy=
array([[[-1.28634727e+00, -6.62697673e-01, -1.41600466e+00, ...,
         -1.11851299e+00, -3.54341954e-01,  1.60578191e-01],
        [-1.74869597e+00,  3.62131707e-02, -2.77533997e-02, ...,
         -5.07575810e-01,  4.46780503e-01, -1.08903386e-01],
        [ 5.33364356e-01, -2.84695864e-01, -4.36593384e-01, ...,
         -3.00415933e-01,  9.02199268e-01, -4.47551101e-01],
        ...,
        [ 6.96243167e-01, -9.97282937e-02,  4.23006713e-01, ...,
          1.44551492e+00, -9.93418455e-01,  6.24212444e-01],
        [-3.10762882e-01,  1.66105390e+00, -8.84898230e-02, ...,
          3.57409805e-01,  8.35292518e-01,  4.40745264e-01],
        [-1.41696858e+00,  6.46081030e-01, -6.11361563e-01, ...,
          8.43923628e-01, -6.61980152e-01,  1.84340811e+00]],

       [[-9.90754887e-02,  1.59307823e-01,  6.32854164e-01, ...,
         -2.16977838e-02,  1.18428223e-01,  1.07513583e+00],
        [ 1.29569232e+00,  4.45667267e-01, 

In [3]:
a = tf.random.normal([35, 8])
b = tf.random.normal([35, 8])
tf.stack([a, b], axis=0) # 堆叠合并成2个班级，班级维度插在最前面

<tf.Tensor: id=26, shape=(2, 35, 8), dtype=float32, numpy=
array([[[-1.33159912e+00, -1.42395186e+00,  2.09396824e-01,
         -1.43785894e+00, -1.38988510e-01, -1.31373668e+00,
          9.33034420e-01, -1.49823642e+00],
        [ 1.21049166e-01, -1.14587879e+00,  7.16687679e-01,
          4.42086339e-01, -1.19627953e+00,  2.14641932e-02,
          1.76442432e+00,  3.39632869e-01],
        [-5.52462220e-01,  1.59271270e-01,  1.80377519e+00,
         -9.06999528e-01,  1.02513862e+00, -1.74118292e+00,
          1.25485754e+00,  3.40369403e-01],
        [-9.25438181e-02, -2.50168681e+00, -8.71337771e-01,
          4.92849141e-01,  8.21384117e-02, -1.20981432e-01,
          5.80012560e-01, -5.46415329e-01],
        [ 1.67983437e+00,  8.32493365e-01, -4.23523962e-01,
          2.07935542e-01, -3.31934750e-01,  8.45987350e-02,
          4.42497790e-01, -2.25783587e+00],
        [ 1.54096591e+00, -6.42864227e-01, -5.03515601e-01,
         -4.04129952e-01, -1.13860384e-01, -3.07935983e-01,
 

### 5.1.2 分割
通过tf.split(x, num_or_size_splits, axis)可以完成张量的分割操作，参数意义为：

x : 待分割张量

num_or_size_splits : 分割方案，为单个数值时，如10，表示等长分割成10份；当为List时，如[2, 4, 2, 2]表示分割成4份，每份长度分别为2，4，2，2

axis : 指定分割的维度索引号

In [5]:
x = tf.random.normal([10, 35, 8])
result = tf.split(x, num_or_size_splits=10, axis=0)
len(result)

10

In [6]:
result[0]

<tf.Tensor: id=41, shape=(1, 35, 8), dtype=float32, numpy=
array([[[-9.50363994e-01,  1.27497211e-01,  1.65808952e+00,
          5.24590313e-01,  3.77247304e-01,  1.65772200e+00,
         -7.75768384e-02,  8.52227092e-01],
        [-8.98461044e-01,  6.29799485e-01,  1.28289926e+00,
          5.19145310e-01,  7.45419562e-02, -9.87127781e-01,
          1.38455224e+00,  5.46585262e-01],
        [ 5.98389888e-03, -7.14431167e-01, -1.28678155e+00,
         -4.06735748e-01, -1.90686464e+00,  8.66526604e-01,
         -7.83563018e-01, -6.83116198e-01],
        [ 1.08923197e+00, -6.08353794e-01, -2.20075989e+00,
         -6.65615499e-01,  1.25136530e+00, -1.70803871e-02,
         -4.17005807e-01, -2.01623335e-01],
        [-2.58017135e+00, -9.08346891e-01,  3.34012687e-01,
         -3.35456952e-02,  6.83011636e-02, -9.41653192e-01,
          2.33196184e-01,  1.73574090e+00],
        [ 5.02639532e-01, -6.22381531e-02,  8.14894736e-01,
          1.37081504e+00, -1.67448485e+00,  9.95096385e-01,
 