# 5 TensorFlow 进阶
## 5.1 合并与分割
### 5.1.1 合并
张量的合并可以使用拼接和堆叠操作实现。拼接操作并不会产生新的维度，仅在现有的维度上合并，而堆叠操作会创建新维度。

In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
a = tf.random.normal([4, 35, 8])
b = tf.random.normal([6, 35, 8])
tf.concat([a, b], axis=0) # 拼接合并，按照第一个维度进行合并

<tf.Tensor: id=13, shape=(10, 35, 8), dtype=float32, numpy=
array([[[-1.6655099e-01,  5.0876176e-01,  1.9515356e-01, ...,
         -3.0072597e-01,  3.9941034e-01, -8.0427133e-02],
        [-1.2480818e+00,  2.0260794e-01,  2.3382192e+00, ...,
         -6.1525530e-01, -8.1931180e-01,  8.3373582e-01],
        [ 9.2896867e-01, -6.8239921e-01,  9.9544775e-01, ...,
          4.1890687e-01,  1.0968835e+00, -9.9566013e-02],
        ...,
        [-4.1516346e-01,  3.7244397e-01, -7.2918051e-01, ...,
         -7.9401314e-01,  4.2793962e-01, -1.0574025e-01],
        [ 3.9214575e-01, -1.1727154e-02,  1.5589416e+00, ...,
          1.2562889e+00, -2.8645304e-01, -1.0339874e+00],
        [-8.2672513e-01, -1.6747319e+00, -1.4987363e+00, ...,
         -8.3875912e-01,  1.2275769e+00, -1.3416686e+00]],

       [[-2.6732665e-01, -1.6919127e+00,  8.8474447e-01, ...,
         -1.6082941e-02,  7.0214939e-01,  1.2638786e+00],
        [ 5.3903025e-01,  2.0676777e+00, -3.2314512e-01, ...,
         -5.2296537e-01

In [3]:
a = tf.random.normal([35, 8])
b = tf.random.normal([35, 8])
tf.stack([a, b], axis=0) # 堆叠合并成2个班级，班级维度插在最前面

<tf.Tensor: id=26, shape=(2, 35, 8), dtype=float32, numpy=
array([[[-7.76612699e-01, -7.42761940e-02,  4.59419817e-01,
         -1.00118923e+00, -1.41467535e+00, -1.11797893e+00,
         -5.58481932e-01, -1.16265297e+00],
        [-4.59121883e-01, -1.86221898e+00, -4.87363100e-01,
         -2.74870723e-01,  5.11918366e-01,  3.09548050e-01,
          1.50456572e+00, -9.20993090e-01],
        [-6.85177505e-01, -1.27041161e+00,  5.65023065e-01,
          9.86582994e-01, -1.45087481e-01,  1.20841432e+00,
         -2.59916514e-01,  1.97323307e-01],
        [ 1.14999449e+00, -5.88034272e-01, -9.79279801e-02,
         -1.27977180e+00,  7.53626585e-01,  8.39281321e-01,
         -5.44508994e-01, -2.04375818e-01],
        [ 1.20707318e-01,  1.35495901e+00, -6.63220048e-01,
         -2.33691439e-01, -6.62210286e-01, -1.60153294e+00,
          7.28152633e-01,  1.06064296e+00],
        [-1.37048078e+00, -8.11779127e-02,  1.87139320e+00,
          5.85969150e-01,  1.75887600e-01, -8.26132357e-01,
 

### 5.1.2 分割
通过tf.split(x, num_or_size_splits, axis)可以完成张量的分割操作，参数意义为：

x : 待分割张量

num_or_size_splits : 分割方案，为单个数值时，如10，表示等长分割成10份；当为List时，如[2, 4, 2, 2]表示分割成4份，每份长度分别为2，4，2，2

axis : 指定分割的维度索引号

In [4]:
x = tf.random.normal([10, 35, 8])
result = tf.split(x, num_or_size_splits=10, axis=0)
len(result)

10

In [5]:
result[0]

<tf.Tensor: id=35, shape=(1, 35, 8), dtype=float32, numpy=
array([[[-0.5146935 , -0.21753521, -2.0372763 ,  0.91928357,
          1.0309988 , -0.3089288 ,  0.01954984,  0.17255533],
        [ 0.02656514, -1.6290119 ,  1.4749793 ,  0.1368364 ,
         -2.0271616 ,  1.1130364 ,  1.176175  , -0.34732983],
        [-0.27589697,  0.4242252 ,  1.1388    , -1.5166408 ,
          1.2565402 ,  0.8352724 , -0.5655488 ,  0.41373906],
        [ 0.7599532 , -0.8351593 , -0.48473015, -1.4160433 ,
          0.8237768 ,  0.09260205, -3.0084043 ,  0.09724119],
        [-0.29902023,  0.286294  , -0.7112256 ,  0.85673195,
          0.5649173 , -0.50272256, -0.6369463 ,  0.57844365],
        [-0.35808644, -0.4208142 , -0.21357016,  1.8958229 ,
          0.3058733 , -2.2627485 , -0.7423865 ,  0.18661118],
        [-0.16467644, -0.58360684,  0.06595649,  1.2522625 ,
         -0.37807944, -0.10492289, -1.0668852 ,  0.42292434],
        [ 0.08371565, -0.2995061 ,  0.00841951, -1.8984222 ,
         -0.6764000

## 5.2 数据统计
### 5.2.1 向量范数
向量范数(Vector Norm)是表征向量“长度”的一种度量方法，他可以推广到张量上。常用的向量范数
* L1范数 : 定义为向量x的所有元素绝对值之和 $ \| x \| _1 = \sum_i{|x_i|} $
* L2范数 : 定义为向量x的所有元素的平方和，再开根号 $ \| x \|_2 = \sqrt{\sum_i |x_i| ^ 2} $
* ∞-范数 : 定义为向量x的所有元素绝对值的最大值 $ \| x \| _ \infty = \max_i \left( | x_i | \right) $

在TensorFlow中，可以通过tf.norm(x, ord)来求解张量的L1、L2、∞等范数，其中指定为1、2时计算L1、L2范数，指定为np.inf时计算∞-范数

In [6]:
x = tf.ones([2, 2])
tf.norm(x, ord=1)

<tf.Tensor: id=51, shape=(), dtype=float32, numpy=4.0>

In [7]:
tf.norm(x, ord=2)

<tf.Tensor: id=56, shape=(), dtype=float32, numpy=2.0>

In [8]:
import numpy as np
tf.norm(x, ord=np.inf)

<tf.Tensor: id=60, shape=(), dtype=float32, numpy=1.0>

### 5.2.2 最值、均值、和
通过tf.reduce_max、tf.reduce_min、tf.reduce_mean、tf.reduce_sum函数可以求解张量在某个维度上的最大、最小、均值、和，也可以求解全局最大、最小、均值、和

In [9]:
x = tf.random.normal([4, 10])
tf.reduce_max(x, axis=1)

<tf.Tensor: id=68, shape=(4,), dtype=float32, numpy=array([1.158345 , 2.1156337, 1.3363562, 1.8492433], dtype=float32)>

In [10]:
# 不指定axis参数时，会计算全局的目标值
tf.reduce_max(x) # 返回结果为标量

<tf.Tensor: id=70, shape=(), dtype=float32, numpy=2.1156337>

在求解误差函数时，通过TensorFLow的MSE误差函数可以求得每个样本得误差，需要计算样本的误差，此时可以通过tf.reduce_mean在样本维度上计算均值

In [11]:
out = tf.random.normal([4, 10]) # 模拟网络预测输出
y = tf.constant([1, 2, 2, 0]) # 模拟真实标签
y = tf.one_hot(y, depth=10)
loss = keras.losses.MSE(y, out) # 计算每个样本的误差
loss = tf.reduce_mean(loss) # 平均误差
loss

<tf.Tensor: id=86, shape=(), dtype=float32, numpy=0.9950267>

除了希望获取张量的最值信息，还希望获得最值所在的位置索引号，例如分类任务的标签预测，就需要知道**概率最大值**所在的索引号，一般把这个位置索引号作为预测类别。

In [12]:
out = tf.random.normal([2, 10])
out = tf.nn.softmax(out, axis=1) # 通过softmax函数转换为概率值
out

<tf.Tensor: id=93, shape=(2, 10), dtype=float32, numpy=
array([[0.15016611, 0.02212241, 0.09410932, 0.01845496, 0.2525919 ,
        0.05495416, 0.05366179, 0.14491086, 0.14033864, 0.06868979],
       [0.02016976, 0.23624495, 0.149242  , 0.04715722, 0.10837556,
        0.05881236, 0.08103057, 0.01178227, 0.15479325, 0.13239214]],
      dtype=float32)>

通过tf.argmax(x, axis)和tf.argmin(x, axis)可以求解在axis维度上，x的最大值、最小值所在的索引号

In [13]:
pred = tf.argmax(out, axis=1) # 选择概率最大的位置
pred

<tf.Tensor: id=95, shape=(2,), dtype=int64, numpy=array([4, 1], dtype=int64)>

## 5.3 张量比较
为了计算分类任务的准确率等指标，一般需要将预测结果和真实标签比较，统计比较结果中正确的数据来计算准确率。

通过tf.softmax获取预测类别

In [14]:
out = tf.random.normal([100, 10])
out = tf.nn.softmax(out, axis=1) # 输出转换为概率
pred = tf.argmax(out, axis=1) # 计算预测值
pred

<tf.Tensor: id=104, shape=(100,), dtype=int64, numpy=
array([9, 1, 1, 0, 1, 1, 7, 4, 7, 5, 7, 6, 7, 7, 4, 5, 2, 6, 2, 2, 6, 2,
       7, 0, 9, 7, 9, 1, 4, 7, 3, 9, 3, 8, 0, 2, 6, 0, 5, 7, 4, 9, 9, 7,
       6, 6, 1, 9, 2, 1, 6, 4, 8, 4, 1, 9, 0, 6, 4, 9, 0, 8, 8, 3, 7, 9,
       8, 3, 1, 8, 3, 7, 0, 2, 7, 0, 2, 4, 6, 8, 5, 7, 8, 1, 3, 5, 8, 2,
       7, 5, 9, 7, 2, 8, 0, 4, 1, 5, 2, 8], dtype=int64)>

In [15]:
# 模型生成真实标签
y = tf.random.uniform([100], dtype=tf.int64, maxval=10)
out = tf.equal(pred, y) # 预测值与真实值比较，返回布尔型的张量
out

<tf.Tensor: id=109, shape=(100,), dtype=bool, numpy=
array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False,  True, False, False, False,  True, False, False,
       False])>

In [16]:
out = tf.cast(out, dtype=tf.float32) # 布尔型转int型
correct = tf.reduce_sum(out) # 统计True的个数
correct.numpy()

9.0

常用比较函数

函数|比较逻辑
:--:|:--:
tf.math.greater|a>b
tf.math.less|a<b
tf.math.greater_equal|a>=b
tf.math.less_equal|a<=b
tf.math.not_equal|a!=b
tf.math.is_nan|a=nan

## 5.4 填充与复制
### 5.4.1 填充
对于图片数据的高和宽、序列信号的长度，维度信号长度可能各不相同。为了方便网络的并行计算，需要将不同长度的数据扩展为相同长度

通过tf.pad(x, paddings)函数实现，参数paddings是包含了多个[Left Padding, Right Padding]的嵌套方案List，如[[0, 0], [2, 1], [1, 2]]表示第一个维度不变，第二个维度左边（起始边）填充两单元，右边（结束端）填充一单元，第三个维度左边（起始边）填充一单元，右边（结束端）填充两单元。

In [17]:
a = tf.constant([1, 2, 3, 4, 5, 6]) # 第一个句子
b = tf.constant([7, 8, 1, 6]) # 第二个句子
b = tf.pad(b, [[0, 2]]) # 句子末尾填充2个0
b

<tf.Tensor: id=116, shape=(6,), dtype=int32, numpy=array([7, 8, 1, 6, 0, 0])>

In [18]:
# 填充后句子张量形状一致，可以Stack在一起
tf.stack([a, b], axis=0)

<tf.Tensor: id=117, shape=(2, 6), dtype=int32, numpy=
array([[1, 2, 3, 4, 5, 6],
       [7, 8, 1, 6, 0, 0]])>

在自然语言处理中，需要加载不同句子长度的数据集，有些句子长度较小，如仅10个单词，部分句子较长，如超过100个单词。为了能够保存在同一张量中，一般会选取能够覆盖大部分句子长度的阈值，如80个单词的句子，截断超过规定长度的部分单词，以IMDB数据集的加载为例。

In [19]:
total_words = 10000 # 设定词汇量大小
max_review_len = 80 # 最大句子长度
embedding_leb = 100  # 词向量长度
# 加载IMDB数据集
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.imdb.load_data(num_words=total_words)
# 将句子填充或截断到相同长度，设置为末尾填充和末尾截断方式
x_train = keras.preprocessing.sequence.pad_sequences(x_train, maxlen=max_review_len, truncating='post', padding='post')
x_test = keras.preprocessing.sequence.pad_sequences(x_test, maxlen=max_review_len, truncating='post', padding='post')
print(x_train.shape, x_test.shape)

(25000, 80) (25000, 80)


### 5.4.2 复制
通过tf.在任意维度将数据重复复制多份

In [20]:
x = tf.random.normal([4, 32, 32, 3])
tf.tile(x, [2, 3, 3, 1])

<tf.Tensor: id=125, shape=(8, 96, 96, 3), dtype=float32, numpy=
array([[[[ 0.42272517, -1.477689  ,  1.2353743 ],
         [ 1.1344113 , -0.97474396, -1.5182681 ],
         [-1.0241717 , -1.1925926 , -0.5333515 ],
         ...,
         [ 2.0638525 , -1.842706  , -0.28137815],
         [-1.578277  , -0.36423704, -0.30340925],
         [-0.55682766, -0.3651025 ,  2.0189774 ]],

        [[ 0.8064248 ,  1.2514116 , -1.5679911 ],
         [-0.8939883 ,  0.49423304, -1.674377  ],
         [-1.2407253 , -1.1345022 , -0.13304053],
         ...,
         [ 2.4090812 ,  0.00650422, -1.669286  ],
         [-0.7151677 , -0.49151453, -1.5538429 ],
         [ 0.0745948 , -0.05651614, -0.09887678]],

        [[ 0.5919222 , -0.58818406,  1.6549172 ],
         [-0.20644432,  1.7309257 , -1.461702  ],
         [ 1.3615128 , -1.5837216 ,  0.2606808 ],
         ...,
         [-0.80193144, -0.7080545 ,  0.08121943],
         [ 0.83843654,  0.4231668 ,  0.47687677],
         [ 1.1721191 , -0.58941144, -0.6

## 5.5 数据限幅
可以通过tf.maximum(x, a)实现数据的下限幅，通过tf.minimum(x, a)实现数据的上限幅

In [21]:
x = tf.range(9)
tf.maximum(x, 2)

<tf.Tensor: id=131, shape=(9,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 8])>

可以通过tf.clip_by_value函数实现上下限幅

In [22]:
x = tf.range(9)
tf.clip_by_value(x, 2, 7)

<tf.Tensor: id=139, shape=(9,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 7])>

## 5.6 高级操作
### 5.6.1 tf.gather
通过tf.gather函数可以收集（分割）数据，相对于切片分割而言，更适合于**不规则**的切片规则

同时tf.gather函数中的索引号可以乱序排列，此时收集的数据也是对应的乱序顺序

In [23]:
x = tf.random.uniform([4, 35, 8], maxval=100, dtype=tf.int32)
tf.gather(x, [0, 3, 8, 11, 12, 26], axis=1)

<tf.Tensor: id=146, shape=(4, 6, 8), dtype=int32, numpy=
array([[[72, 37, 40, 76, 54, 19, 88, 90],
        [46, 34, 11, 93, 46, 48, 29, 98],
        [11, 81, 38, 98,  9, 80, 97, 42],
        [22, 29, 23, 14, 37, 73, 28, 27],
        [34, 30, 22, 54, 45, 99, 50, 39],
        [75, 21, 73, 98, 45, 98, 21, 46]],

       [[39, 82, 49, 66, 12, 57,  0, 17],
        [87, 44, 82, 71, 77, 81, 10, 58],
        [47, 15, 32, 72,  1, 82, 19, 29],
        [63, 98, 48,  6, 66,  7, 87, 64],
        [60, 97, 64, 14, 36, 73, 71, 77],
        [10,  7, 25, 15, 69, 36, 88,  7]],

       [[33,  8, 16, 21, 42, 49,  2, 85],
        [52, 40, 34,  5, 23, 65, 64, 46],
        [24, 51, 26,  4, 76, 54, 50, 59],
        [59, 59, 75,  1, 83, 87,  5, 45],
        [73, 89,  0, 30, 42, 99, 29, 36],
        [51, 89, 22, 72, 68, 44, 77, 95]],

       [[70, 64, 63, 42, 63, 96, 45, 99],
        [50, 46, 25, 82, 52, 53, 82, 98],
        [92, 59, 12, 84, 71, 32, 56, 33],
        [ 3, 33, 58,  1, 47, 85, 67, 96],
        [35, 

In [24]:
tf.gather(x, [4, 2], axis=2)

<tf.Tensor: id=149, shape=(4, 35, 2), dtype=int32, numpy=
array([[[54, 40],
        [43,  2],
        [75, 43],
        [46, 11],
        [42, 17],
        [66, 38],
        [36, 92],
        [83, 25],
        [ 9, 38],
        [72, 45],
        [28, 73],
        [37, 23],
        [45, 22],
        [22, 58],
        [54, 87],
        [80, 79],
        [78, 78],
        [11, 21],
        [59, 34],
        [96, 78],
        [60, 12],
        [60,  5],
        [95, 58],
        [29, 90],
        [70, 41],
        [96, 65],
        [45, 73],
        [49, 43],
        [82, 47],
        [90, 88],
        [ 1, 13],
        [50, 79],
        [14, 26],
        [82, 25],
        [49, 79]],

       [[12, 49],
        [61, 54],
        [38, 75],
        [77, 82],
        [72, 94],
        [74,  2],
        [74, 98],
        [97, 67],
        [ 1, 32],
        [59, 93],
        [88, 92],
        [66, 48],
        [36, 64],
        [91, 24],
        [13, 21],
        [89, 35],
        [85, 34],
    

### 5.6.2 tf.gather_nd
通过tf.gather_nd函数，可以通过指定每次采样点的多维坐标来实现采样多个点的目的。

In [25]:
tf.gather_nd(x, [[1, 1], [2, 2], [3, 3]]) # 根据多维坐标收集数据

<tf.Tensor: id=151, shape=(3, 8), dtype=int32, numpy=
array([[50, 97, 54, 79, 61, 93, 21, 15],
       [27, 44, 41, 41, 88,  9, 70, 90],
       [50, 46, 25, 82, 52, 53, 82, 98]])>

### 5.6.3 tf.boolean_mask
通过掩码(mask)的方式进行采样。

掩码List长度必须与给定维度的长度相同

In [26]:
# 根据掩码方式采样班级，给出掩码和维度索引
tf.boolean_mask(x, mask=[True, False, False, True], axis=0)

<tf.Tensor: id=179, shape=(2, 35, 8), dtype=int32, numpy=
array([[[72, 37, 40, 76, 54, 19, 88, 90],
        [22, 97,  2, 47, 43, 54, 18, 29],
        [62, 32, 43, 59, 75, 61, 54, 66],
        [46, 34, 11, 93, 46, 48, 29, 98],
        [34, 78, 17, 52, 42, 99, 34, 23],
        [ 6,  4, 38, 24, 66, 84, 38, 83],
        [ 5, 94, 92, 80, 36, 29, 14, 90],
        [81, 38, 25, 90, 83, 47, 84, 70],
        [11, 81, 38, 98,  9, 80, 97, 42],
        [60, 24, 45, 25, 72, 23, 16, 54],
        [62, 23, 73,  0, 28, 23, 59, 28],
        [22, 29, 23, 14, 37, 73, 28, 27],
        [34, 30, 22, 54, 45, 99, 50, 39],
        [66, 65, 58, 23, 22, 78, 27, 26],
        [23, 76, 87, 67, 54, 91, 74, 52],
        [34, 80, 79, 86, 80,  7, 63, 39],
        [98, 41, 78, 82, 78, 14, 97, 66],
        [74,  3, 21, 88, 11, 50, 96, 16],
        [90, 90, 34, 88, 59, 75, 13, 59],
        [74, 11, 78, 59, 96, 93, 41, 39],
        [43, 36, 12, 88, 60, 99, 89, 71],
        [54, 15,  5, 46, 60, 81, 81, 89],
        [ 7, 68, 5

### 5.6.4 tf.where
通过tf.where(cond, a, b)操作可以根据cond条件的真假从参数A或B中读取数据

In [30]:
a = tf.ones([3, 3])
b = tf.zeros([3, 3])
# 构造采样条件
cond = tf.constant([[True, False, False], [False, True, False], [True, True, False]])
tf.where(cond, a, b)

<tf.Tensor: id=193, shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 1., 0.]], dtype=float32)>

通过比较得到所有正数的掩码，通过tf.where提取此掩码处True元素的索引坐标，通过tf.gather_nd即可恢复出所有正数的元素

In [31]:
x = tf.random.normal([3, 3])
mask = x > 0
indices = tf.where(mask)
tf.gather_nd(x, indices)

<tf.Tensor: id=203, shape=(4,), dtype=float32, numpy=array([0.14118505, 0.28343686, 0.81879574, 0.14411093], dtype=float32)>

### 5.6.5 tf.scatter_nd
通过tf.scatter_nd(indices, updates, shape)函数可以高效地刷新张量的部分数据，但是这个函数只能在全0的白板张量上面执行刷新操作

In [32]:
# 构造需要刷新数据的位置
indices = tf.constant([[4], [3], [1], [7]])
# 构造需要写入的数据
updates = tf.constant([4.4, 3.3, 1.1, 7.7])
# 在长度为8的全0向量上根据indices写入updates数据
tf.scatter_nd(indices, updates, [8])

<tf.Tensor: id=207, shape=(8,), dtype=float32, numpy=array([0. , 1.1, 0. , 3.3, 4.4, 0. , 0. , 7.7], dtype=float32)>

### 5.6.6 tf.meshgrid
通过tf.meshgrid函数可以方便地生成二维网络的采样点坐标，方便可视化等应用场合

In [33]:
x = tf.linspace(-8., 8, 100)
y = tf.linspace(-8., 8, 100)
x, y = tf.meshgrid(x, y) # 生成网格点，并内部拆分后返回
print(x.shape)
print(y.shape)

(100, 100)
(100, 100)


In [34]:
z = tf.sqrt(x**2 + y**2)
z = tf.sin(z) / z

In [35]:
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure()
ax = Axes3D(fig)
ax.contour3D(x.numpy(), y.numpy(), z.numpy(), 50)
plt.show()

<Figure size 640x480 with 1 Axes>