# 5 TensorFlow 进阶
## 5.1 合并与分割
### 5.1.1 合并
张量的合并可以使用拼接和堆叠操作实现。拼接操作并不会产生新的维度，仅在现有的维度上合并，而堆叠操作会创建新维度。

In [2]:
import tensorflow as tf
from tensorflow import keras

In [3]:
a = tf.random.normal([4, 35, 8])
b = tf.random.normal([6, 35, 8])
tf.concat([a, b], axis=0) # 拼接合并，按照第一个维度进行合并

<tf.Tensor: id=13, shape=(10, 35, 8), dtype=float32, numpy=
array([[[-0.9494822 ,  2.5431597 , -0.40442273, ..., -1.4060324 ,
          1.2702708 , -1.8734655 ],
        [-0.18108627, -0.14031637,  0.36038345, ..., -1.088843  ,
         -0.7036153 , -0.23866399],
        [ 0.05180838,  1.5381438 ,  0.40975595, ...,  0.74285066,
         -0.13425827,  1.5841261 ],
        ...,
        [ 1.8234318 ,  0.9409237 , -1.1883783 , ..., -1.4045463 ,
          1.0605857 ,  1.1107134 ],
        [ 1.0384915 , -0.56127197, -0.8566415 , ...,  0.56372637,
          0.7185293 ,  0.09187102],
        [ 0.5486011 , -2.7981052 , -0.67039484, ...,  0.2526747 ,
          2.3071399 ,  0.87364256]],

       [[-0.08669128, -0.37971213, -0.15468667, ..., -0.42986652,
         -1.5244774 ,  1.316444  ],
        [-0.8415281 ,  2.4870257 ,  1.7489843 , ..., -2.3333228 ,
          1.7234373 , -0.29858476],
        [ 1.2566748 ,  1.2006077 , -0.1620701 , ...,  1.4792588 ,
          2.9826639 , -2.7215984 ],
       

In [4]:
a = tf.random.normal([35, 8])
b = tf.random.normal([35, 8])
tf.stack([a, b], axis=0) # 堆叠合并成2个班级，班级维度插在最前面

<tf.Tensor: id=26, shape=(2, 35, 8), dtype=float32, numpy=
array([[[-9.48591232e-01,  8.49158585e-01,  6.90637678e-02,
         -1.27187920e+00,  6.12839341e-01, -2.98849434e-01,
         -4.33708310e-01, -1.70191038e+00],
        [-1.42722213e+00, -3.60572636e-01, -5.52810490e-01,
          4.03456956e-01,  8.94683719e-01,  1.09515458e-01,
          6.42442703e-01,  6.93381652e-02],
        [-2.30008498e-01, -5.74329376e-01,  1.35472703e+00,
          6.14044592e-02,  4.08001244e-01,  9.72785205e-02,
         -1.49098933e+00, -1.37717700e+00],
        [-1.25713229e+00,  4.18009430e-01, -1.12506866e+00,
         -1.34725869e+00,  1.29452392e-01, -3.83881301e-01,
          3.12210131e+00,  1.77861869e-01],
        [ 1.25665891e+00, -1.40041900e+00,  7.65174389e-01,
          1.81244850e-01, -4.64993387e-01,  9.29110348e-01,
         -7.28348792e-01,  5.67815721e-01],
        [-6.13055289e-01,  1.19525385e+00, -5.22926688e-01,
          2.92000473e-01,  8.84409323e-02,  3.28523546e-01,
 

### 5.1.2 分割
通过tf.split(x, num_or_size_splits, axis)可以完成张量的分割操作，参数意义为：

x : 待分割张量

num_or_size_splits : 分割方案，为单个数值时，如10，表示等长分割成10份；当为List时，如[2, 4, 2, 2]表示分割成4份，每份长度分别为2，4，2，2

axis : 指定分割的维度索引号

In [5]:
x = tf.random.normal([10, 35, 8])
result = tf.split(x, num_or_size_splits=10, axis=0)
len(result)

10

In [6]:
result[0]

<tf.Tensor: id=35, shape=(1, 35, 8), dtype=float32, numpy=
array([[[ 0.54047406, -1.0915779 , -1.3340214 , -0.37306318,
         -1.1135378 ,  0.15336657, -0.30756813,  0.13461201],
        [ 1.8096522 , -0.7529655 ,  2.0407565 , -0.23347968,
         -0.67726356,  0.17954282,  0.5216824 ,  1.1187892 ],
        [-1.6816794 ,  1.5668458 ,  0.34327736, -0.6404742 ,
          1.1734502 , -1.0678293 ,  0.06103148, -1.1001816 ],
        [-0.0537792 , -0.5365313 , -0.14118813, -0.84667486,
         -1.6475607 , -0.72301376,  1.9237607 , -0.8162584 ],
        [-0.52602774,  0.22472836,  1.5075494 ,  0.95265144,
         -0.8452854 ,  0.85700417,  0.8175743 , -0.05925577],
        [ 0.04264487, -1.0626525 , -0.4887242 , -0.38769254,
         -0.5400635 ,  0.7011508 , -0.14334306, -0.21177132],
        [ 1.8760787 , -0.45286435,  1.4604266 ,  0.25525197,
          0.9416096 , -0.6005876 ,  0.8263013 , -0.6618376 ],
        [ 1.1932373 , -0.26771578,  0.06055946,  0.08682491,
          0.5383104

## 5.2 数据统计
### 5.2.1 向量范数
向量范数(Vector Norm)是表征向量“长度”的一种度量方法，他可以推广到张量上。常用的向量范数
* L1范数 : 定义为向量x的所有元素绝对值之和 $ \| x \| _1 = \sum_i{|x_i|} $
* L2范数 : 定义为向量x的所有元素的平方和，再开根号 $ \| x \|_2 = \sqrt{\sum_i |x_i| ^ 2} $
* ∞-范数 : 定义为向量x的所有元素绝对值的最大值 $ \| x \| _ \infty = \max_i \left( | x_i | \right) $

在TensorFlow中，可以通过tf.norm(x, ord)来求解张量的L1、L2、∞等范数，其中指定为1、2时计算L1、L2范数，指定为np.inf时计算∞-范数

In [7]:
x = tf.ones([2, 2])
tf.norm(x, ord=1)

<tf.Tensor: id=51, shape=(), dtype=float32, numpy=4.0>

In [8]:
tf.norm(x, ord=2)

<tf.Tensor: id=56, shape=(), dtype=float32, numpy=2.0>

In [9]:
import numpy as np
tf.norm(x, ord=np.inf)

<tf.Tensor: id=60, shape=(), dtype=float32, numpy=1.0>

### 5.2.2 最值、均值、和
通过tf.reduce_max、tf.reduce_min、tf.reduce_mean、tf.reduce_sum函数可以求解张量在某个维度上的最大、最小、均值、和，也可以求解全局最大、最小、均值、和

In [10]:
x = tf.random.normal([4, 10])
tf.reduce_max(x, axis=1)

<tf.Tensor: id=68, shape=(4,), dtype=float32, numpy=array([0.801991 , 1.4799871, 1.4679644, 1.6905991], dtype=float32)>

In [11]:
# 不指定axis参数时，会计算全局的目标值
tf.reduce_max(x) # 返回结果为标量

<tf.Tensor: id=70, shape=(), dtype=float32, numpy=1.6905991>

在求解误差函数时，通过TensorFLow的MSE误差函数可以求得每个样本得误差，需要计算样本的误差，此时可以通过tf.reduce_mean在样本维度上计算均值

In [12]:
out = tf.random.normal([4, 10]) # 模拟网络预测输出
y = tf.constant([1, 2, 2, 0]) # 模拟真实标签
y = tf.one_hot(y, depth=10)
loss = keras.losses.MSE(y, out) # 计算每个样本的误差
loss = tf.reduce_mean(loss) # 平均误差
loss

<tf.Tensor: id=86, shape=(), dtype=float32, numpy=0.8446905>

除了希望获取张量的最值信息，还希望获得最值所在的位置索引号，例如分类任务的标签预测，就需要知道**概率最大值**所在的索引号，一般把这个位置索引号作为预测类别。

In [13]:
out = tf.random.normal([2, 10])
out = tf.nn.softmax(out, axis=1) # 通过softmax函数转换为概率值
out

<tf.Tensor: id=93, shape=(2, 10), dtype=float32, numpy=
array([[0.05417096, 0.03614845, 0.02558594, 0.10654559, 0.14584568,
        0.06972463, 0.12052655, 0.04656256, 0.35709286, 0.03779678],
       [0.03472913, 0.11297537, 0.04543633, 0.07309355, 0.06318901,
        0.38780805, 0.06158558, 0.03101049, 0.11415957, 0.07601292]],
      dtype=float32)>

通过tf.argmax(x, axis)和tf.argmin(x, axis)可以求解在axis维度上，x的最大值、最小值所在的索引号

In [14]:
pred = tf.argmax(out, axis=1) # 选择概率最大的位置
pred

<tf.Tensor: id=95, shape=(2,), dtype=int64, numpy=array([8, 5], dtype=int64)>

## 5.3 张量比较
为了计算分类任务的准确率等指标，一般需要将预测结果和真实标签比较，统计比较结果中正确的数据来计算准确率。

通过tf.softmax获取预测类别

In [17]:
out = tf.random.normal([100, 10])
out = tf.nn.softmax(out, axis=1) # 输出转换为概率
pred = tf.argmax(out, axis=1) # 计算预测值
pred

<tf.Tensor: id=122, shape=(100,), dtype=int64, numpy=
array([4, 0, 1, 9, 8, 6, 8, 9, 7, 3, 3, 9, 5, 5, 6, 1, 6, 9, 2, 3, 9, 0,
       8, 0, 2, 3, 4, 4, 8, 0, 8, 6, 3, 8, 7, 3, 8, 7, 7, 9, 5, 0, 7, 5,
       2, 4, 3, 5, 1, 1, 2, 5, 6, 9, 4, 0, 6, 2, 6, 0, 7, 4, 6, 4, 4, 3,
       4, 5, 0, 1, 7, 7, 2, 7, 1, 8, 8, 7, 9, 7, 2, 7, 0, 3, 5, 4, 2, 1,
       4, 7, 2, 6, 1, 1, 1, 5, 0, 7, 5, 5], dtype=int64)>

In [19]:
# 模型生成真实标签
y = tf.random.uniform([100], dtype=tf.int64, maxval=10)
out = tf.equal(pred, y) # 预测值与真实值比较，返回布尔型的张量
out

<tf.Tensor: id=132, shape=(100,), dtype=bool, numpy=
array([False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False,  True, False, False, False,  True, False, False,
       False])>

In [22]:
out = tf.cast(out, dtype=tf.float32) # 布尔型转int型
correct = tf.reduce_sum(out) # 统计True的个数
correct.numpy()

10.0

常用比较函数

函数|比较逻辑
:--:|:--:
tf.math.greater|a>b
tf.math.less|a<b
tf.math.greater_equal|a>=b
tf.math.less_equal|a<=b
tf.math.not_equal|a!=b
tf.math.is_nan|a=nan

## 5.4 填充与复制
### 5.4.1 填充
对于图片数据的高和宽、序列信号的长度，维度信号长度可能各不相同。为了方便网络的并行计算，需要将不同长度的数据扩展为相同长度